FROM mono:slim
WORKDIR /app
COPY ./config/jsign_4.1_all.deb ./
RUN apt update &&\
	apt install --no-install-recommends mono-complete mono-vbnc mono-fastcgi-server4 nginx locales curl cron -y &&\
	apt install ./jsign_4.1_all.deb -y &&\
	sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen &&\
	dpkg-reconfigure --frontend=noninteractive locales &&\
	update-locale LANG=en_US.UTF-8 &&\
	rm -rf /var/lib/apt/lists/*
ENV NAME=UCDialplans \
    LANG="en_US.UTF-8" \
    MONO_ASPNET_WEBCONFIG_CACHESIZE=200 
COPY ./config/start_server ./start_server
COPY ./config/kl_codesign.* ./
COPY ./config/fastcgi_params /etc/nginx/fastcgi_params
COPY ./config/default-config /etc/nginx/sites-enabled/default
COPY ./config/nginx.conf /etc/nginx/nginx.conf
COPY ./config/mysql_net_v4.5.2 /app/mysql_net_v4.5.2
COPY ./config/emailupdates /etc/cron.daily
COPY ./data/wwwroot /var/www
RUN gacutil /i mysql_net_v4.5.2/MySql.Data.dll &&\
	gacutil /i /usr/lib/mono/4.5/Facades/System.Diagnostics.Process.dll &&\
	chmod +x start_server &&\
	chmod +x /etc/cron.daily/emailupdates
RUN useradd -u 1000 hoff 
	RUN chmod o+r -R /var/www 
	RUN chmod o+w /var/www/rulesets 
	RUN chmod o+r -R /etc/nginx
RUN chmod o+rw -R /var/log/nginx
RUN chmod o+rw -R /var/lib/nginx
RUN chmod o+rw -R /run
RUN mkdir /home/hoff
RUN chown hoff /home/hoff
USER hoff
EXPOSE 8080
CMD ./start_server
