InsecureSkipVerify = true
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/star_ucdialplans_com.pem"
      keyFile = "/certs/star_ucdialplans_com.key"

[log]
  filepath = "/var/log/traefik.log"
  level = "INFO"
